export const assetsSections = [
    {
      title: "ODF Sustainability",
      cards: [
        {
          key: "ihhl",
          label: "IHHL",
          bgColor: "#ECFDF5",
          textColor: "#065F46",
          border: "#A7F3D0",
          bgImg: "/ODF.png",
        },
        {
          key: "community_sanitary",
          label: "Community Sanitary Complex (CSC)",
          bgColor: "#ECFDF5",
          textColor: "#065F46",
          border: "#A7F3D0",
          bgImg: "/ODF.png",
        },
        {
          key: "total_csc",
          label: "Total No. of CSCs in Shala Darpan (Schools)",
          bgColor: "#ECFDF5",
          textColor: "#065F46",
          border: "#A7F3D0",
          bgImg: "/ODF.png",
        },
      ],
    },

    {
      title: "Solid Waste Management",
      cards: [
        {
          key: "segregation_hh",
          label: "Segregation Bins at HH Level",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "segregation_public",
          label: "Segregation Bins at Public Places",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "compost_pit",
          label: "Community Compost Pit",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "segregation_sheds",
          label: "Segregation Sheds(RRC)",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "Tricycles_Manual",
          label: "Tricycles (Manual)",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "e_rickshaws_bettery",
          label: "E-Rickshaws/Bettery operated Vehicles",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
        {
          key: "Motorized_Vehicles",
          label: "Motorized Vehicles",
          bgColor: "#F0F9FF",
          textColor: "#364153",
          border: "#F0F9FF",
          bgImg: "/solidWast.png",
        },
      ],
    },
    {
      title: "Liquid Waste Management",
      cards: [
        {
          key: "Soak_Leach_Pits",
          label: "Soak/Magic/Leach pits at HH Level",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "Community_Soak_Leach_Pits",
          label: "Community Soak/Magic/Leach pits",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "WSP_Waste_Stabilization_Pond",
          label: "WSP (Waste Stabilization Pond)",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "Dewats",
          label: "Dewats",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "Wetland",
          label: "Wetland",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "Any_other_Trenching",
          label: "Any Other (Trenching, Phytorids, etc.)",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
        {
          key: "Drainage_channels",
          label: "Drainage channels",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/liquidWast.png",
        },
      ],
    },
    {
      title: "Plastic Waste Management Unit(PWMUs)",
      cards: [
        {
          key: "Total_no_established_pwmu",
          label: "Total No. of Established PWMU",
          bgColor: "#EEEDFF",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/plasticWaste.png",
        },
        {
          key: "Total_no_Blocks_Covered_Under_PWMU",
          label: "Total No. of Blocks Covered Under PWMU",
          bgColor: "#EEEDFF",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/plasticWaste.png",
        },
        {
          key: "Total_No_of_Urban_MRFs",
          label: "Total No. of Urban MRFs",
          bgColor: "#EEEDFF",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/plasticWaste.png",
        },
        {
          key: "Total_No_Blocks_Covered_Under_Urban_MRFs",
          label: "Total No. of Blocks Covered Under Urban MRFs",
          bgColor: "#EEEDFF",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/plasticWaste.png",
        },
      ],
    },
    {
      title: "Faecal Sludge Management (FSM)",
      cards: [
        {
          key: "No_twin_pits_Toilets",
          label: "No. of twin pits Toilets",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "Single_pits_Toilets",
          label: "No. of Single pits Toilets",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "Septic_bank_Toilets",
          label: "No. of Septic tank Toilets",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "Retrofitted_toilets",
          label: "No. of Retrofitted toilets",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "Mechanized_DeSludging",
          label: "Mechanized De-Sludging",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "FSTPs",
          label: "No. of FSTPs",
          subLabels: [
            "rural",
            "urban"
          ],
          // width: "279px",
          bgColor: "#FFEDF3",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/FSM.png",
        },
        {
          key: "GOBARDhan_Project",
          label: "GOBAR-dhan Project",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/gobar.png",
          width: "558px",
        },
      ],
    },
    {
      title: "Door to Door Waste Collection, Segregation & Disposal Activities",
      cards: [
        {
          key: "Total_gps",
          label: "Total No. GPs",
          bgColor: "#FFEDD5",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorhouse.png",
        },
        {
          key: "Total_Work_Sanctioned_Status",
          label: "Total No. of Work Sanctioned",
          subLabels: [
            "Tender",
            "Self GP",
            "CSR/NGO",
            "SHG"
          ],
          width: "558px",
          bgColor: "#FFEDD5",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorimg.png",
        },
        {
          key: "Total_Expenditure_Amt",
          label: "Total Expenditure Amt. (Rs in Lakhs)",
          bgColor: "#FFEDD5",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorimg.png",
        },
        {
          key: "Total_Vehicles_Collection_transportation_waste",
          label: "Total No. of Vehicles for Collection and transportation of waste ",
          bgColor: "#FFEDD5",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoortruck.png",
        },
        {
          key: "Total_Persons_Deployed",
          label: "Total No. of Persons Deployed (Sanitation Worker)",
          bgColor: "#FFEDD5",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorman.png",
        },
        {
          key: "Total_House_Hold_Covered",
          label: "Total No. of House Hold Covered",
          bgColor: "#FEFCE8",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorimg.png",
        },
        {
          key: "work_status",
          label: "Work Status",
          subLabels: [
            "Start",
            "Running",
            "Completed"
          ],
          bgColor: "#FEFCE8",
          // width: "279px",
          textColor: "#364153",
          border: "#E5E7EB",
          bgImg: "/doortodoorimg.png",
        },
      ],
    },
  ];