export const assetsSections = [
  {
    title: "odfSustainability",
    cards: [
      {
        key: "ihhl",
        label: "ihhl",
        bgColor: "#ECFDF5",
        textColor: "#065F46",
        border: "#A7F3D0",
        bgImg: "/ODF.png",
      },
      {
        key: "community_sanitary",
        label: "communitySanitaryComplex",
        bgColor: "#ECFDF5",
        textColor: "#065F46",
        border: "#A7F3D0",
        bgImg: "/ODF.png",
      },
      {
        key: "total_csc",
        label: "totalCsCsInSchools",
        bgColor: "#ECFDF5",
        textColor: "#065F46",
        border: "#A7F3D0",
        bgImg: "/ODF.png",
      },
    ],
  },

  {
    title: "solidWasteManagement",
    cards: [
      {
        key: "segregation_hh",
        label: "segregationBinsAtHH",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "segregation_public",
        label: "segregationBinsAtPublicPlaces",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "compost_pit",
        label: "communityCompostPit",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "hh_compost_pit",
        label: "householdCompostPit",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "segregation_sheds",
        label: "segregationSheds",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "Tricycles_Manual",
        label: "tricyclesManual",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "e_rickshaws_bettery",
        label: "eRickshawsBatteryVehicles",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
      {
        key: "Motorized_Vehicles",
        label: "motorizedVehicles",
        bgColor: "#F0F9FF",
        textColor: "#364153",
        border: "#F0F9FF",
        bgImg: "/solidWast.png",
      },
    ],
  },
  {
    title: "liquidWasteManagement",
    cards: [
      {
        key: "Soak_Leach_Pits",
        label: "soakMagicLeachPitsHH",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "Community_Soak_Leach_Pits",
        label: "communitySoakMagicLeachPits",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "WSP_Waste_Stabilization_Pond",
        label: "wspWasteStabilizationPond",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "Dewats",
        label: "dewats",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "Wetland",
        label: "wetland",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "Any_other_Trenching",
        label: "anyOtherTrenching",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
      {
        key: "Drainage_channels",
        label: "drainageChannels",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/liquidWast.png",
      },
    ],
  },
  {
    title: "plasticWasteManagement",
    cards: [
      {
        key: "Total_no_established_pwmu",
        label: "totalEstablishedPwmu",
        bgColor: "#EEEDFF",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/plasticWaste.png",
      },
      {
        key: "Total_no_Blocks_Covered_Under_PWMU",
        label: "totalBlocksCoveredPwmu",
        bgColor: "#EEEDFF",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/plasticWaste.png",
      },
      {
        key: "Total_No_of_Urban_MRFs",
        label: "totalUrbanMrfs",
        bgColor: "#EEEDFF",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/plasticWaste.png",
      },
      {
        key: "Total_No_Blocks_Covered_Under_Urban_MRFs",
        label: "totalBlocksCoveredUrbanMrfs",
        bgColor: "#EEEDFF",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/plasticWaste.png",
      },
    ],
  },
  {
    title: "fsm",
    cards: [
      {
        key: "No_twin_pits_Toilets",
        label: "twinPitToilets",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },
      {
        key: "Single_pits_Toilets",
        label: "singlePitToilets",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },
      {
        key: "Septic_bank_Toilets",
        label: "septicTankToilets",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },
      {
        key: "Retrofitted_toilets",
        label: "retrofittedToilets",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },
      {
        key: "Mechanized_DeSludging",
        label: "mechanizedDesludging",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },
      {
        key: "FSTPs",
        label: "fstps",
        subLabels: [
          "rural",
          "urban"
        ],
        // width: "279px",
        bgColor: "#FFEDF3",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/FSM.png",
      },

    ],
  },
  {
    title: 'gobardhanProject',
    cards: [
      {
        key: "total_sanctioned",
        label: "totalSanctioned",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/gobar.png",
      },
      {
        key: "total_functional",
        label: "totalFunctional",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/gobar.png",
      },
      {
        key: "Gas_Production",
        label: "gasProduction",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/gobar.png",
      },
    ]
  },
  {
    title: "doorToDoorWasteCollection",
    cards: [
      {
        key: "Total_gps",
        label: "totalGps",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorhouse.png",
      },
      {
        key: "Total_Work_Sanctioned_Status",
        label: "totalWorkSanctioned",
        subLabels: [
          "contractorsThroughTender",
          "gpThroughPlacementAgency",
          "gpThroughCSR",
          "gpThroughSHG",
          "mixedModel",
        ],
        width: "840px",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorimg.png",
      },
      {
        key: "Total_Expenditure_Amt",
        label: "totalExpenditureAmt",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorimg.png",
      },
      {
        key: "not_started_gp",
        label: "notStartedGp",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorhouse.png",
      },
      {
        key: "Total_Vehicles_Collection_transportation_waste",
        label: "totalVehiclesForWasteCollection",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "Total_Persons_Deployed",
        label: "totalPersonsDeployed",
        bgColor: "#FFEDD5",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorman.png",
      },
      {
        key: "Total_House_Hold_Covered",
        label: "totalHouseholdCovered",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorimg.png",
      },
      {
        key: "work_status",
        label: "workStatus",
        subLabels: [
          "start",
          "running",
          "completed"
        ],
        bgColor: "#FEFCE8",
        // width: "279px",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorimg.png",
      },
    ],
  },
  {
    title: 'bartanBank',
    cards: [
      {
        key: "bartan_bank",
        label: "bartanBankInformation",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoorimg.png",
      },
    ]
  }, {
    title: 'vehicle',
    cards: [
      {
        key: "ownedTricycles",
        label: "ownedTricycles",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "ownedERickshaws",
        label: "ownedERickshaws",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "ownedMotorizedVehicles",
        label: "ownedMotorizedVehicles",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "contractorTricycles",
        label: "contractorTricycles",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "contractorERickshaws",
        label: "contractorERickshaws",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
      {
        key: "contractorMotorizedVehicles",
        label: "contractorMotorizedVehicles",
        bgColor: "#FEFCE8",
        textColor: "#364153",
        border: "#E5E7EB",
        bgImg: "/doortodoortruck.png",
      },
    ]
  },
];